### ISSUE TITLE
Things to add

### ISSUE THREAD

**Issue by enoch85** [kyrofa/owncloud-snap#1]
- [ ] [Let's Encrypt](https://github.com/enoch85/ownCloud-VM/tree/master/lets-encrypt) (Needs to be improved)
- [ ] Web GUI on boot that gives the user instructions and the possibility to change default password and user. Also change timezone and default language.
- [ ] A script that pre-sets every setting to ownCloud. crontab, max upload etc. 
- [ ] Automatic updates via cronjob
- [ ] Plug n Play network settings (show IP in Web GUI etc)
- [ ] Contacts app, Calendar app, Documents app.
- [ ] Boot from SD Card and move everything else to the HDD, (possible to script this?)
- [ ] Webmin (for easier maintenance of the server as it gives a GUI)
- [ ] ...

**Comment by kyrofa** [comment]
I'm going to split these into separate issues so we can track them individually. Note that there are a number of things that I don't believe belongs here:
- Web GUI is unnecessary as initial wizard allows for setting up admin user/password.
- Automatic updates happen by default in Ubuntu Core-- no cronjob needed.
- Moving the writeable partition to the HDD is a separate problem from this .snap, and should be tracked separately. This .snap will work either way.
- Plug n Play network settings should be handled by the mDNS daemon in the .snap.
- Webmin will be useless on Ubuntu Core:
  - Everything is already auto-updated
  - The .snap should configure what it needs on its own
  - You won't be able to access shipped devices anyway, so what's the point? :stuck_out_tongue: 
  - If something needs to be updated, you release a new version of the .snap, not remotely administer each device. Make sense?

**Comment by enoch85** [comment]
@kyrofa Makes sense. :)
