### ISSUE TITLE
on upgrade, Pi goes in maintenance mode

### ISSUE THREAD

**Issue by jospoortvliet** [kyrofa/owncloud-snap#14]
On upgrade from 8.2.2 to 9.0, the Pi seems to be set to go to into maintenance mode. Running the upgrade via the web UI risks time-out problems (esp on the slow Pi with potentially 1TB of data) so the snappy upgrade process has to run 
`
$ sudo -u apache php occ upgrade
`
followed by:
`
$ sudo -u apache php occ maintenance:mode --off
`
(or the Snappy equivalents - `$ owncloud.occ upgrade` and such)

We need to think about how to deal with errors but that's a future thing.

**Comment by jospoortvliet** [comment]
the occ command also gives an error ATM:

```
ubuntu@localhost:~$ owncloud.occ status
PHP Warning:  fopen(/var/lib/snaps/owncloud.canonical/9.0.0ubuntu1/owncloud/config/config.php): failed to open stream: Permission denied in /snaps/owncloud.canonical/9.0.0ubuntu1/htdocs/lib/private/config.php on line 187
PHP Warning:  flock() expects parameter 1 to be resource, boolean given in /snaps/owncloud.canonical/9.0.0ubuntu1/htdocs/lib/private/config.php on line 197
An unhandled exception has been thrown:
Exception: Could not acquire a shared lock on the config file /var/lib/snaps/owncloud.canonical/9.0.0ubuntu1/owncloud/config/config.php in /snaps/owncloud.canonical/9.0.0ubuntu1/htdocs/lib/private/config.php:198
Stack trace:
#0 /snaps/owncloud.canonical/9.0.0ubuntu1/htdocs/lib/private/config.php(58): OC\Config->readData()
#1 /snaps/owncloud.canonical/9.0.0ubuntu1/htdocs/lib/base.php(138): OC\Config->__construct('/var/lib/snaps/...')
#2 /snaps/owncloud.canonical/9.0.0ubuntu1/htdocs/lib/base.php(508): OC::initPaths()
#3 /snaps/owncloud.canonical/9.0.0ubuntu1/htdocs/lib/base.php(1108): OC::init()
#4 /snaps/owncloud.canonical/9.0.0ubuntu1/htdocs/console.php(46): require_once('/snaps/owncloud...')
#5 /snaps/owncloud.canonical/9.0.0ubuntu1/htdocs/occ(11): require_once('/snaps/owncloud...')
#6 {main}ubuntu@localhost:~$ 
```

EDIT: PEBKAC - needs  sudo: 

```
$ubuntu@localhost:~$ sudo owncloud.occ status
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
  - installed: true
  - version: 9.0.0.19
  - versionstring: 9.0.0
  - edition: 
```

Excellent!

**Comment by kyrofa** [comment]
Indeed, the upgrade needs to be ironed out for initial release. I have your syslog and will hopefully be able to use it to determine what went wrong (I haven't looked at it just yet).

**Comment by kyrofa** [comment]
After looking at your syslog, this appeared to be due to your mysql flaking at the wrong time. It probably would have succeeded a second time (e.g. if you restarted the apache service). How did this happen? I'm not sure-- Apache checks to make sure mysql has a pid file before continuing. But the best fix is to probably fail to start apache if the upgrade fails, and systemd will restart it so it can try again.
