### ISSUE TITLE
Add NTP

### ISSUE THREAD

**Issue by jospoortvliet** [kyrofa/owncloud-snap#15]
NTP ensures the server always has the correct time and, seeing how the ownCloud syncing mechanism partially relies on time and date of files, this is helpful.

**Comment by kyrofa** [comment]
Snappy Ubuntu Core utilizes systemd-timedated for this:

```
$ timedatectl
      Local time: Thu 2016-03-24 12:32:48 UTC
  Universal time: Thu 2016-03-24 12:32:48 UTC
        RTC time: n/a
       Time zone: n/a (UTC, +0000)
 Network time on: yes
NTP synchronized: yes
 RTC in local TZ: no
```

**Comment by jospoortvliet** [comment]
Cool ;-)
