### ISSUE TITLE
Decrease memory reserved for GPU

### ISSUE THREAD

**Issue by jospoortvliet** [kyrofa/owncloud-snap#18]
See [this page](http://elinux.org/RPiconfig#Memory) - you can set the GPU memory from default 64 to 16. This is a `boot/config.txt` setting, named `gpu_mem`.

```
$ tail /boot/config.txt -n1
gpu_mem=16
```
## results:

Before:

```
$ cat /proc/meminfo|grep Mem
MemTotal:         481288 kB
MemFree:          433492 kB
```

After:

```
$ cat /proc/meminfo|grep Mem
MemTotal:         497544 kB
MemFree:          450076 kB
```

From [this page](https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=39764).

Not a massive saving but every bit helps! :hear_no_evil: :see_no_evil: :speak_no_evil:

**Comment by WaaromZoMoeilijk** [comment]
Working on this one since all the overclocking is in config.txt. Will put it up for review soon.

Edit: https://github.com/owncloud/ubuntu-snap/issues/15

**Comment by kyrofa** [comment]
This isn't something that can be solved in the snap, so closing here.
