### ISSUE TITLE
libssl-dev missing from list of Apache dependencies

### ISSUE THREAD

**Issue by oparoz** [kyrofa/owncloud-snap#20]
When snapcrafting the ownCloud snap in a clean environment, Apache fails during the build step, complaining about some missing OpenSSL headers.

The fix is to modify the Apache python plugin to include:
- libssl-dev
- libssl1.0.0
- zlib1g-dev

@kyrofa

**Comment by kyrofa** [comment]
Thanks for catching that @oparoz. The fix would be to add `libssl-dev` to the Apache plugin's build-packages, and `libssl1.0.0` and `zlib1g` to its stage-packages.

**Comment by oparoz** [comment]
Just to be sure, `apt-cache` tells me we need `zlib1g-dev`, but you want to use the non-dev version for staging?
Here is what's installed:

```
zlib1g/xenial,now 1:1.2.8.dfsg-2ubuntu4 amd64 [installed]
zlib1g-dev/xenial,now 1:1.2.8.dfsg-2ubuntu4 amd64 [installed,automatic]
```

**Comment by kyrofa** [comment]
Right, build packages go into `build-packages`, runtime packages into `stage-packages`. In this case, *-dev packages into `build-packages`, and their runtime equivalents into `stage-packages`. `libssl-dev` depends upon `zlibg-dev`, so no need to name that one explicitly.

**Comment by oparoz** [comment]
OK, I think I got it, thanks.
