### ISSUE TITLE
Remove all htaccess files and convert them to Directory directives

### ISSUE THREAD

**Issue by oparoz** [kyrofa/owncloud-snap#29]
## Why

https://httpd.apache.org/docs/2.4/howto/htaccess.html

"In general, you should only use .htaccess files when you don't have access to the main server configuration file. There is, for example, a common misconception that user authentication should always be done in .htaccess files, and, in more recent years, another misconception that mod_rewrite directives must go in .htaccess files. This is simply not the case. You can put user authentication configurations in the main server configuration, and this is, in fact, the preferred way to do things. Likewise, mod_rewrite directives work better, in many respects, in the main server configuration."

"However, in general, **use of .htaccess files should be avoided when possible**. Any configuration that you would consider putting in a .htaccess file, can just as effectively be made in a <Directory> section in your main server configuration file."

"The first of these [reason to avoid it] is performance. When AllowOverride is set to allow the use of .htaccess files, httpd will look in every directory for .htaccess files. **Thus, permitting .htaccess files causes a performance hit, whether or not you actually even use them!** Also, the .htaccess file is loaded every time a document is requested.

Further note that httpd must look for .htaccess files in all higher-level directories, in order to have a full complement of directives that it must apply. (See section on how directives are applied.) Thus, if a file is requested out of a directory /www/htdocs/example, httpd must look for the following files:

```
/.htaccess
/www/.htaccess
/www/htdocs/.htaccess
/www/htdocs/example/.htaccess
```

And so, for each file access out of that directory, there are 4 additional file-system accesses, even if none of those files are present. (Note that this would only be the case if .htaccess files were enabled for /, which is not usually the case.)

In the case of RewriteRule directives, in .htaccess context **these regular expressions must be re-compiled with every request to the directory**, whereas in main server configuration context they are compiled once and cached. Additionally, the rules themselves are more complicated, as one must work around the restrictions that come with per-directory context and mod_rewrite. Consult the Rewrite Guide for more detail on this subject."
## How

Write one `<Directory>` per `.htaccess` file in the [Apache config file](https://github.com/kyrofa/owncloud-snap/blob/master/src/owncloud/apache_config)
## Caveats

All updates provided by ownCloud have to be backported into our config file

**Comment by kyrofa** [comment]
This isn't a problem in the current snap-- it uses `AllowOverride None`. There's an issue in that we don't use the .htaccess files at all (note that's no longer an issue with #62), but that's not this issue so I'll close it here.

**Comment by oparoz** [comment]
Well, by including the `.htaccess` files, you're doing exactly what's described here ;) and #62 is still missing a couple of includes.
