### ISSUE TITLE
Automatically set things up via script

### ISSUE THREAD

**Issue by oparoz** [kyrofa/owncloud-snap#34]
The current snap lets the user pick an admin username and password, but this is preventing us from performing advanced features such as automatically enabling official apps.
### Plan
- Pick a username and password via script
- Present the information to the user
- Make it available via SSH in case something bad happens

@kyrofa @jospoortvliet @ezraholm50 @enoch85 @miska

**Comment by kyrofa** [comment]
I personally don't feel like this provides a very good out-of-the-box experience. I thought enabling apps was as simple as dropping them in the apps folder?

**Comment by oparoz** [comment]
> I thought enabling apps was as simple as dropping them in the apps folder

Unfortunately, no. Apps need to be enabled via occ, but we' can't use occ until ownCloud is installed. Same problem with the cron, you can't set it to a real cron if ownCloud is not installed.

**Comment by enoch85** [comment]
I do this in my VMs already, you could get inspiration from there.

**Comment by oparoz** [comment]
Sure, we just need to all agree that this is the way forward.

**Comment by enoch85** [comment]
@oparoz There have been discussions about that the terminal scares people off, and as this project is aiming to a clientele that are non-tech-guys I think we should avoid the terminal as much as possible. With that said, are you talking about a script that are run _before_ we ship the image/final product?

**Comment by oparoz** [comment]
IIRC, your VM doesn't require people to log in via shell, no? Isn't there a page displayed in the browser until the user logs in for the first time?

**Comment by enoch85** [comment]
Well, the [first setup](https://github.com/enoch85/ownCloud-VM/blob/master/production/owncloud-startup-script.sh) is run via shell, but ownCloud are installed before that, and I try to put as much as possible in the install script. The startup script is "straight forward" and everything is made so that the user interact as little as possible. Some configurations has to be done in the startup script, like e.g. changing SSH keys and stuff so that everything differs between the final VMs for security reasons.

The user have to enter the following:
- Set new passwords
- Set new timzone
- Set static IP (is automated, but the user can change LAN address if he/she wish)
- Enter domain for Let's Encrypt

Everything else is automated.

**Comment by oparoz** [comment]
Ah, that won't work then.

The other option is to do it like any other appliance vendor, set a default password and ask the user to change it.
After all, the shell is accessible via ubuntu/ubuntu and can do much more damage.

**Comment by enoch85** [comment]
> The other option is to do it like any other appliance vendor, set a default password and ask the user to change it.

Default password is 'owncloud' the user change it in the scripts. So I guess I'm like all the other appliance vendors. :)

**Comment by enoch85** [comment]
I also made a $variable for the default user last week, so that's it's possible to change that as well. It could also be done via an IF argument. And if the user wants to change the default user, delete the old one. <-- The last part is not done in my VM though, the variable has to be changed before the script is run.

(In my VM the default user is 'ocadmin')

**Comment by kyrofa** [comment]
> Unfortunately, no. Apps need to be enabled via occ, but we' can't use occ until ownCloud is installed. Same problem with the cron, you can't set it to a real cron if ownCloud is not installed.

This feels like a bug in ownCloud to me. This is something that should be possible, or customized installations are kinda pointless. I wanted to ship some more default apps too, but I don't think I'm willing to sacrifice the user experience for it here.

**Comment by enoch85** [comment]
@kyrofa Is it possible to pre-install via a script on snap? In that case: https://github.com/enoch85/ownCloud-VM/blob/master/production/owncloud_install_production.sh#L324-L369

**Comment by kyrofa** [comment]
@enoch85 yeah I could do something similar to that, but @oparoz just said you can't do it with `occ` until it's installed, and `occ` doesn't consider ownCloud to be installed until the user has setup the admin account. Or did I misunderstand? @oparoz when you say "installed," do you mean installed as far as `occ` is concerned, or installed = the snap installed?

**Comment by enoch85** [comment]
@kyrofa You can use `occ` before the user is setup afaik.

**Comment by kyrofa** [comment]
@enoch85 yeah but the command set is limited. Not sure if this is one of the limitations.

**Comment by oparoz** [comment]
@enoch85 ^^^^

**Comment by enoch85** [comment]
@kyrofa Why not pre-set a user then, that the user then can delete after they've set up a new one in the "Users" section inside owncloud? That gives us total control of what's done, and that also gives the everything that `occ` can offer. 

Maybe not as user friendly to ask the user to create a new user, but that's the best option if you ask me. On the other hand, is it user friendly not to be ship it with no apps pre-installed?

**Comment by kyrofa** [comment]
@enoch85 that means people _must_ read documentation to determine how to login to the thing. I don't like making the user jump through hoops that shouldn't be necessary. I think it's more friendly to not ship extra apps preinstalled-- the user can always install them if they wish, and not install them if they don't.

**Comment by enoch85** [comment]
@kyrofa Is the plan to direct the user to the login page directly, or run some SSH prior to the login? If the case is SSH before, then the user could get the information from there, _or_ the user could be directed to a page with all the default info.

**Comment by kyrofa** [comment]
@enoch85 this device shouldn't require anyone to use SSH (at least eventually, heh). Eventually I'd like to disable it by default.

**Comment by enoch85** [comment]
@kyrofa Ok, yes, that would be the best actually. But question remains, what do you think of a default landing page? Something like this: https://github.com/enoch85/ownCloud-VM/blob/master/production/index.php

**Comment by enoch85** [comment]
Sidenote: Both [my VM](https://www.techandme.se/pre-configured-owncloud-installaton/), and the official ownCloud VM does this way, why not the snap?

**Comment by kyrofa** [comment]
> But question remains, what do you think of a default landing page?

I think it's a workaround for an ownCloud bug that should be fixed.

> Sidenote: Both my VM, and the official ownCloud VM does this way, why not the snap?

Then I'm surprised it hasn't been fixed yet! It also begs another question: If the official ownCloud VM preloads apps beyond the default, why aren't they the default?

**Comment by enoch85** [comment]
@kyrofa 

> Then I'm surprised it hasn't been fixed yet! It also begs another question: If the official ownCloud VM preloads apps beyond the default, why aren't they the default?

It's not preloaded in the official VM (there is an option to do it), just in mine. But as I said, it make things much easier during build as `occ` is available.

**Comment by kyrofa** [comment]
> But as I said, it make things much easier during build as occ is available.

I'm not debating that, I just think it provides an inferior user experience :smiley: . I think rpi2-specific performance tweaks are going to have to go into the fork anyway, so perhaps this should be solved there?

**Comment by enoch85** [comment]
@kyrofa 

I'm just arguing for a pre-set user (installation in total), as it make things alot easier. And to be honest, is it _that_ hard to read something like "Default user: ocadmin" i.e.? :)

> I think rpi2-specific performance tweaks are going to have to go into the fork anyway, so perhaps this should be solved there?

Let's hope so.

**Comment by kyrofa** [comment]
> I'm just arguing for a pre-set user (installation in total), as it make things alot easier.

I understand; that's not something I want to add here.

> And to be honest, is it that hard to read something like "Default user: ocadmin" i.e.? :)

Of course not :) . But it's not about difficulty, it's about a polished experience. I believe prompting the user to create an admin account and have only the default apps initially provides a more polished experience than having a landing page explaining how to login and needing to change the password (or create another account) only to get some non-default apps that they can install themselves.

ownCloud should implement this via `autoconfig.php` or something similar.

**Comment by enoch85** [comment]
> ownCloud should implement this via autoconfig.php or something similar.

Agreed. :)

**Comment by oparoz** [comment]
> If the official ownCloud VM preloads apps beyond the default, why aren't they the default?

@kyrofa  - To prevent bloatware and breakage. It's not because apps are official that they're always ready for a new dot zero launch. It often takes a couple of releases to get them right.
By cherry picking the ones we want, we can offer a better out-of-the-box experience, because the first thing users will do is to install apps, only to find out that it completely messes up their installation.

The big problem, is that recommended apps which are sideloaded are marked as experimental..., so we may have to back off here.
Having a landing page would allow us to make some recommendations covering both settings and apps, but as mentioned above, this is probably something to keep for the ownCloud branch, allowing the community to release something which works like the VM, if we can set users up without forcing them to use SSH.

Don't forget @kyrofa that you may not be able to set the cron without occ, so users will have to read some documentation to get the most out of their box.

**Comment by kyrofa** [comment]
> Don't forget @kyrofa that you may not be able to set the cron without occ, so users will have to read some documentation to get the most out of their box.

Yeah I've been thinking about that. Since it's database-only (i.e. not controlled via `config.php`) I may introduce support for this via `autoconfig.php`. Think such a change would be accepted upstream? Also, think we can get any ownCloud support for pre-loaded apps?

**Comment by oparoz** [comment]
> Think such a change would be accepted upstream?

I don't see why not. It would be very useful to be able to do more from `autoconfig.php`

> Also, think we can get any ownCloud support for pre-loaded apps?

Maybe. There could be 2 stages to autoconfig and this would be part of stage 2. The code to install apps is in a class which could be instantiated there.
There would still be the problem about apps being marked as experimental though.

**Comment by kyrofa** [comment]
I'm going to close this here. Feel free to track in the fork if this is something you want to do.
