### ISSUE TITLE
No exposed mysql client 

### ISSUE THREAD

**Issue by danielholm** [kyrofa/owncloud-snap#37]
Hi, 

I'm about to migrate my old ownCloud instance to a Raspberry pi 2 running ownCloud Snap. Config and files should be somewhat easy, but how do I migrate - import the old - database? There seem to be no mysql client available to use. 

Cheers, 
Daniel

**Comment by kyrofa** [comment]
Thanks Daniel! Indeed, the mysql client is not exposed in the snap. I'll try to make that happen in the next release.

**Comment by danielholm** [comment]
Splendid! Thank you :)

**Comment by oparoz** [comment]
@danielholm - You don't need to wait, the mysql client works just fine if you give the socket as argument

```
# /snaps/owncloud.<developer>/current/bin/mysql -S /var/lib/snaps/owncloud.<developer>/current/mysql/mysql.sock -u root -p
```
