### ISSUE TITLE
Suggestion to remove extra-configuration from apache plugin

### ISSUE THREAD

**Issue by oparoz** [kyrofa/owncloud-snap#38]
I think the approach taken by the other parts works better, we don't have to recompile mysql to introduce changes to the config files and scripts. It's a pain to have to recompile apache every time we make a change to the vhost.

So I vote for removing `extra-configuration` and to create a new part.

**Comment by kyrofa** [comment]
My only problem with that is it doesn't allow the Apache plugin to stand alone (i.e. it would generate a non-working Apache snap if used on its own). For this particular snap I agree with you-- we should ship our own config in another part. We can actually do that without changing the Apache plugin though-- we can just filter out the configs it generates using the `stage` and `snap` keywords and ship our own replacement.

**Comment by oparoz** [comment]
> My only problem with that is it doesn't allow the Apache plugin to stand alone

Sure, but I think anybody using the plugin is going to face the same problem.

> we can just filter out the configs it generates using the stage and snap keywords

Is it really necessary? Wouldn't it be better to make it possible to just comment out `extra-configuration` and `startup-script`?

I would ship the plugin as a git repo coming with 2 snapcraft.yaml examples showing how it's possible to include everything in one part or to split app and config in 2 parts.

**Comment by oparoz** [comment]
Ah I see that it will complain, yes...

```
        if self.options.startup_script and not os.path.isfile(self.options.startup_script):
            raise RuntimeError(
                'startup-script file "{}" doesn\'t exist'.format(
                    self.options.startup_script))

        if self.options.extra_configuration and not os.path.isfile(self.options.extra_configuration):
            raise RuntimeError(
                'extra-configuration file "{}" doesn\'t exist'.format(
                    self.options.extra_configuration))
```

**Comment by kyrofa** [comment]
> Sure, but I think anybody using the plugin is going to face the same problem.

Perhaps so, perhaps not. I don't want to ship a plugin that doesn't work by itself, that's all.

> Is it really necessary? Wouldn't it be better to make it possible to just comment out extra-configuration and startup-script?

That's already possible-- it only errors out if you specify them and they don't exist. We just don't need to specify them. Though not specifying `startup-script` either means we need to switch the Apache service around (which is fine as long as we don't need to define any extra environment variables).

**Comment by oparoz** [comment]
Maybe in a future version of Snapcraft you could make xyz-customisation a part of the xyz part and always copy those files, even if the xyz has already been compiled? That way monolithic plugins would still contain everything but be less of a pain to configure?

**Comment by oparoz** [comment]
Closing since the plugin will stay the same and since there is a workaround we can use.
