### ISSUE TITLE
Use a custom apps folder for user added ownCloud apps

### ISSUE THREAD

**Issue by oparoz** [kyrofa/owncloud-snap#42]
It's possible to keep the apps folder read-only and to use another one called, let's say `userapps`, to store apps that users will have downloaded from the app store or installed themselves.

That's the doc.
https://doc.owncloud.org/server/9.0/admin_manual/configuration_server/config_sample_php_parameters.html#apps

This could be useful to make sure the apps folder only contains apps which comes with the current release of ownCloud as old apps can be incompatible.
Apps enabled by the user can, of course, still introduce issue, but it will be easier to focus on those ones when trying to find the root cause of a problem.
## 

@kyrofa

**Comment by kyrofa** [comment]
Yeah great idea, and would make upgrades a lot easier. Big :+1: from me.
