### ISSUE TITLE
Add http/2 support to Apache

### ISSUE THREAD

**Issue by oparoz** [kyrofa/owncloud-snap#43]
Once TLS is enabled (#44), it makes sense to use HTTP/2 to speed up operations.

@kyrofa @jospoortvliet @ezraholm50 @enoch85 @miska

**Comment by kyrofa** [comment]
I'm a little confused-- are we talking about HTTP/2 or HTTPS?

**Comment by oparoz** [comment]
HTTP/2, I'll make the OP clearer. TLS support is in #44

**Comment by oparoz** [comment]
- [x] Let's wait for https://github.com/kyrofa/owncloud-snap/issues/48
