### ISSUE TITLE
Increase max upload in php.ini

### ISSUE THREAD

**Issue by enoch85** [kyrofa/owncloud-snap#5]
https://github.com/enoch85/ownCloud-VM/blob/master/beta/owncloud_install.sh#L140-L150

Changes needs to be done to ownClouds .htaccess file as well.

**Comment by enoch85** [comment]
https://github.com/owncloud/pi-image/issues/12

**Comment by jospoortvliet** [comment]
@kyrofa could you hint at how to make this change?

**Comment by jospoortvliet** [comment]
I believe it could be done changing php.ini around here:
https://github.com/kyrofa/owncloud-snap/blob/rolling/src/apache/Makefile#L57

**Comment by oparoz** [comment]
This will be a user configurable setting, part of #39

**Comment by kyrofa** [comment]
@oparoz uploads by default go into /tmp, which is currently tmpfs. I'd like to change PHP's upload directory, but I'm not clear on whether or not that directory will just continually grow if not tmpfs. Will PHP or ownCloud clear out uploads after they've finished (or if they've failed)?

**Comment by oparoz** [comment]
Yeah, I've moved it to `${SNAP_DATA}/var/tmp` for PHP-FPM and the directory is kept clean. There will probably be some problems with some failed files, but if the writeable partition is a HD, there shouldn't be an issue with space.
