### ISSUE TITLE
mdns-publisher uses components which may not be compatible with go 1.6

### ISSUE THREAD

**Issue by oparoz** [kyrofa/owncloud-snap#51]
https://github.com/miekg/dns

> We support the last two versions of Go, currently: 1.4 and 1.5.

@kyrofa I'm mentioning it because this part fails when stripping on arm.

https://bugs.launchpad.net/snappy/+bug/1569280

**Comment by oparoz** [comment]
Comments from #Launchpad

> (12:12:36 PM) cjwatson: It's also odd that ldd apparently exits non-zero without writing anything to stderr.
> (12:13:09 PM) cjwatson: (Also also, I wish I'd never looked at the run_output function.  Why on earth doesn't it just use subprocess's ordinary environment-handling facilities?)

**Comment by kyrofa** [comment]
mdns-publisher works fine on Go 1.6-- this is a [snapcraft bug](https://bugs.launchpad.net/snapcraft/+bug/1569280) and will be tracked there.
