### ISSUE TITLE
Only responds to local domain?

### ISSUE THREAD

**Issue by danielholm** [kyrofa/owncloud-snap#55]
(Though connected trough own OpenVPN) I am not able to connect to the ownCloud Pi Drive on my network. SSH works, but not web. Local domain does not work trough OpenVPN so I tried to connect to the device's IP but no go. Is "owncloud.local" the only way of connecting, and if so why? Trying to set up a port forward to the device's port 80 does not work either.

**Comment by halfsight5000** [comment]
Hi, I would be curious to know more. I can get mine to respond on the IP address and also I gave it an FQDN from my BIND.

Have you tried http:// with the IP address? Also, if you go to a PHP file in /var/lib/snaps/owncloud.canonical/current/owncloud/config/config.php you should be able to set trusted IP address, or see what IP address was set.

Edit:

I think that's the snap I am in, double check!

**Comment by danielholm** [comment]
Hi again,

Nope, I can't get mine to respond to the local IP and therefore can't bind a FQDN. All other devices on my local works as they should. I also checked the config (thank you for that :) and it does confirm my hypothesis: the snap does only respond to "owncloud.local":
`'trusted_domains' => 
  array (
    0 => 'owncloud.local',
  ),`

And about that, I would like to have nano on the device, but I will ask for that in a separate issue - I am obviously unable to learn vi...

**Comment by kyrofa** [comment]
> Is "owncloud.local" the only way of connecting, and if so why?

No, you should definitely be able to connect via IP-- the mDNS stuff is just for convenience. Are you sure Apache is running?

**Comment by kyrofa** [comment]
> I also checked the config (thank you for that :) and it does confirm my hypothesis: the snap does only respond to "owncloud.local"

No, the trusted domain is set to the initial domain you use to visit the device-- if you initially use `owncloud.local` (which it seems you did) it's set to that. If you used the IP address the first time, it's set to the IP. After the initial visit, if you change what you're using to connect you must add it as a trusted domain (which you can do as an ownCloud admin).

**Comment by danielholm** [comment]
It should be.. I have not made any modifications to the system since I got the ownCloud Pi Drive. I jsut rebooted after editing the config. I'm nor that well educated about the Ubuntu Core, but a quick "service apache2 status" says inactive (dead). Trying to start it by "sudo service apache start" is a no go, but probably due to the snappy container (correct?). How else do I know if Apache is running?

**Comment by danielholm** [comment]
> After the initial visit, if you change it you must add it (which you can do as an ownCloud admin).

I've added a few more lines to the trusted_domains (I am unable to access the ownCloud admin page):

```
'trusted_domains' => 
  array (
    0 => 'owncloud.local',
    1 => '192.168.X.Y',
  ),
```

Could this be a show stopper?
`'overwrite.cli.url' => 'http://owncloud.local',`

**Comment by danielholm** [comment]
It does indeed look like only port 22 is open on my device, though..

Also my owncloud.log has no prints since the 13th so yeah, It does indeed look like Apache is dead. How do I start it?

**Comment by danielholm** [comment]
Ok, so after looking around a bit I believe I found the command for the web service, after which being ran prints this:
`sudo /snaps/owncloud.canonical/9.0.0ubuntu1/bin/httpd -d /snaps/owncloud.canonical/9.0.0ubuntu1 -D FOREGROUND
/snaps/owncloud.canonical/9.0.0ubuntu1/bin/httpd: error while loading shared libraries: libaprutil-1.so.0: cannot open shared object file: No such file or directory`

**Comment by kyrofa** [comment]
Yeah you won't be able to run that directly. I don't have a system in front of me at the moment, but try `snappy service owncloud status` or some version of that command.

**Comment by danielholm** [comment]
`owncloud   owncloud    enabled; loaded; active (running)`

**Comment by kyrofa** [comment]
Note you should also checkout your syslog-- anything interesting there? As well as a `ps ax | grep apache` perhaps?

**Comment by danielholm** [comment]
ps ax | grep apache
`6376 pts/0    S+     0:00 grep --color=auto apache`

The last 10 lines from syslog:
`Apr 18 13:46:41 localhost systemd[1]: owncloud_owncloud_8.0.2.006-16.04.service: Service hold-off time over, scheduling restart.
Apr 18 13:46:41 localhost systemd[1]: Stopped owncloud for snappy docker framework.
Apr 18 13:46:41 localhost systemd[1]: Started owncloud for snappy docker framework.
Apr 18 13:46:41 localhost ubuntu-core-launcher[6934]: kickinz1/owncloud-8.0.2-sqlite3-armhf
Apr 18 13:46:43 localhost ubuntu-core-launcher[6934]: /snaps/owncloud.canonical/8.0.2.006-16.04/bin/owncloud: line 62: docker.armhf: command not found
Apr 18 13:46:43 localhost ubuntu-core-launcher[6934]: /snaps/owncloud.canonical/8.0.2.006-16.04/bin/owncloud: line 63: docker.armhf: command not found
Apr 18 13:46:43 localhost ubuntu-core-launcher[6934]: /snaps/owncloud.canonical/8.0.2.006-16.04/bin/owncloud: line 64: docker.armhf: command not found
Apr 18 13:46:43 localhost systemd[1]: owncloud_owncloud_8.0.2.006-16.04.service: Main process exited, code=exited, status=127/n/a
Apr 18 13:46:43 localhost systemd[1]: owncloud_owncloud_8.0.2.006-16.04.service: Unit entered failed state.
Apr 18 13:46:43 localhost systemd[1]: owncloud_owncloud_8.0.2.006-16.04.service: Failed with result 'exit-code'.
`

Could it be because I installed the docker snap the other day?

**Comment by kyrofa** [comment]
Uhh... ownCloud for snappy docker framework? That's _ancient_ stuff... how did you even get it on 16.04?

**Comment by danielholm** [comment]
snappy install docker..

Followed the snappy doc and just wanted to try to install something.

**Comment by kyrofa** [comment]
The ownCloud package used to require docker back in 15.04. It has since been replaced with the native one (which repository), but it looks like you somehow got the 15.04 version which uses docker. Can you show me the output of `snappy list`?

**Comment by danielholm** [comment]
snappy list
Name                Date       Version             Developer 
canonical-pi2-linux 2016-02-03 4.3.0-1006-3        canonical 
docker              2016-03-03 1.6.2.005-16.04.1-2 canonical 
owncloud-pi2        2016-03-17 3.0owncloud2        kyrofa  
owncloud            2016-01-26 8.0.2.006-16.04     canonical 
ubuntu-core         2016-03-08 16.04.0-15.armhf    canonical

**Comment by kyrofa** [comment]
Wow... this got very messed up. Okay let me make sure I understand:
1. You flashed the initial owncloud image (which is why owncloud-pi2 is there).
2. Things worked (?)
3. You installed docker via `snappy install docker`
4. Chaos ensued? Did it never work again at that point?

**Comment by danielholm** [comment]
And now I am of course unable to remove that snap since "framework still in use by: owncloud".

**Comment by kyrofa** [comment]
Of course not :stuck_out_tongue: .

**Comment by danielholm** [comment]
1. I got the system sent to me together with a HD, a case and stuff. All the snaps, beside docker, was there. https://owncloud.org/blog/pioneer-our-owncloud-pi-drives/
2. Things worked.
3. Correct.
4. Yes. I never tried to access the owncloud instance again after, until now, since I've left that location (and now I've set up an VPN, but I did not have access to http until that).

**Comment by danielholm** [comment]
What If i try to remove the packages and then install them again? Meaning both owncloud as well as docker. Then install owncloud only?

**Comment by kyrofa** [comment]
@danielholm okay I'm going to have to duplicate locally. I'll have to get back to you. If you're okay ~~potentially~~ definitely losing ownCloud files and settings you can try removing the packages and reinstalling owncloud. Something like this:

```
$ sudo snappy remove owncloud
$ sudo snappy remove docker
$ sudo snappy purge owncloud
$ sudo snappy purge docker
$ sudo snappy install owncloud
```

Note you could also reflash.

**Comment by danielholm** [comment]
I'll try to remove and reinstall (I'm doing it all remotely through VPN so I cant reflash).

**Comment by kyrofa** [comment]
> I'm doing it all remotely through VPN so I cant reflash

Ah right. We'll get you back up and running, then :smiley: .

**Comment by danielholm** [comment]
Much appreciated :D

**Comment by kyrofa** [comment]
Sorry about this-- I think you hit a Snappy bug here, but I'll know more once I experiment myself. Until then, stay away from Docker, okay?

**Comment by danielholm** [comment]
Installed and rebooting now.

Haha, I promise!

**Comment by danielholm** [comment]
It is alive! Thank you so very, very much. Closing this issue now. Sorry for the inconvenience.

**Comment by kyrofa** [comment]
> Sorry for the inconvenience.

Back at you. We'll figure out what happened, thanks for the patience with the beta :smiley: .

**Comment by danielholm** [comment]
Certainly. No worries :) I'm looking forward to the future with this project.

**Comment by kyrofa** [comment]
> I think you hit a Snappy bug here, but I'll know more once I experiment myself

You actually hit a store bug! They're still reworking some pieces before release. This should no longer be an issue-- thank you for reporting this :smiley: .

**Comment by danielholm** [comment]
Well what do you know. Well, thank you :)
