### ISSUE TITLE
Unable to determine library dependencies for mdns-publisher

### ISSUE THREAD

**Issue by oparoz** [kyrofa/owncloud-snap#58]
This is the new error reported by the snap builder

```
Unable to determine library dependencies for b'/build/owncloud-snap/snap/bin/mdns-publisher'
```

It doesn't seem to have a negative impact as the publisher is still able to push the correct IP.

**Comment by oparoz** [comment]
The message is only shown when building for armhf

**Comment by kyrofa** [comment]
Yeah this is to be expected on armhf. I believe it's due to Go having rudimentary library support only implemented on amd64, which means Go binaries on armhf are still completely static; being unable to determine their dependencies isn't an issue.
