### ISSUE TITLE
mysql-client should not require sudo

### ISSUE THREAD

**Issue by oparoz** [kyrofa/owncloud-snap#63]
Unlike other commands `mysql-client` requires sudo because mysql files have unusual permissions compared to the other installed apps.

**Comment by oparoz** [comment]
Hmmm looks like occ needs sudo as well. It would be good to figure out why and if that can be avoided.

**Comment by kyrofa** [comment]
All files in SNAP_DATA are owned by root, and have relatively restrictive permissions. I don't see a problem with this.

**Comment by oparoz** [comment]
It's just confusing, but it's Snappy's fault, not this snap's. We log in as ubuntu, but require sudo for a lot of operations because of the file ownership. Some commands work without it, but the best thing to do seems to become root as soon as we're logged in.
