### ISSUE TITLE
got wrong message with 'mdns-publisher'

### ISSUE THREAD

**Issue by howywang** [kyrofa/owncloud-snap#8]
> Pulling mdns-publisher 
> env GOPATH=/home/u/Downloads/snap/owncloud/parts/mdns-publisher/go go get -t -d github.com/kyrofa/mdns-publisher
> Building mdns-publisher 
> env GOPATH=/home/u/Downloads/snap/owncloud/parts/mdns-publisher/go go install github.com/kyrofa/mdns-publisher
> # github.com/miekg/dns
> 
> **github.com/miekg/dns/dnssec.go:257: undefined: crypto.Signer
> github.com/miekg/dns/dnssec.go:321: undefined: crypto.Signer
> github.com/miekg/dns/sig0.go:16: undefined: crypto.Signer
> Failed doing build for mdns-publisher: Command '['/bin/sh', '/tmp/tmp61dy5irh', 'env', 'GOPATH=/home/u/Downloads/snap/owncloud/parts/mdns-publisher/go', 'go', 'install', 'github.com/kyrofa/mdns-publisher']' returned non-zero exit status 2**

How can I do? Many thanks!

**Comment by kyrofa** [comment]
First of all, you know you can just install this from the Snappy store, right? If not, check out the README for how.

But you can of course build it yourself. In your case, your version of Go is too old (I believe you need at lease 1.3). What version of Ubuntu are you using to run Snapcraft? Try adding the ppa:ubuntu-lxc/lxd-stable to your system and update your version of Go.

**Comment by howywang** [comment]
update:
My go version is go1.3.3 linux/amd64
I will add ppa:ubuntu-lxc/lxd-stable and try to update.
I have updated Go to go1.6beta2 linux/amd64
And snapcraft your package again.

Thanks Kyrofa,

I saw the owncloud 8.0.2.006 at Snappy store, but your ownCloud version is 8.2.2.
May I know what's the snap name for your package in Snappy store?
I am using Ubuntu 15.04 (64 bit), I will check out my Go version later.

**Comment by kyrofa** [comment]
You're probably seeing the Docker-based one. To install my version, I'll take an excerpt from the README:

> Note that there's currently a limitation in the Snappy store that prevents multiple uploads of the same package, even if they support different architectures. This will be resolved soon, but until then, the package names need to be different. So the command to install ownCloud depends on your architecture:
> - armhf (e.g. the Raspberry Pi 2):
>   - sudo snappy install owncloud.kyrofa
> - amd64:
>   - sudo snappy install owncloud-amd64.kyrofa

Eventually (perhaps as early as Monday), the store will support that and it'll just be owncloud.kyrofa.

**Comment by howywang** [comment]
Yes, I saw that from README, I just want to study how to make a snap with your package.
Now I think my problem is Go version too old. I am tring to build a snap with your package now.
Thank you

**Comment by howywang** [comment]
i can use the following command to install and owcloud is work well.

> amd64:
> sudo snappy install owncloud-amd64.kyrofa

But I still meet some wrong messages during snapcraft after updating GO lang to go1.6beta2
And my snapcraft  version is 1.0.

The wrong messages as below:
make[1]: Leaving directory '/home/u/Downloads/owncloud-snap-master/parts/mysql/build/mysql/build'
patching file support-files/mysql.server
Staging mysql 
Snapping mysql 
/tmp/tmpygtkw4rc: 5: export: -L/home/u/Downloads/owncloud-snap-master/snap/usr/lib: bad variable name
Traceback (most recent call last):
  File "/usr/bin/snapcraft", line 33, in <module>
    snapcraft.main.main()
  File "/usr/lib/python3/dist-packages/snapcraft/main.py", line 148, in main
    args.func(args)
  File "/usr/lib/python3/dist-packages/snapcraft/cmds.py", line 98, in assemble
    snap(args)
  File "/usr/lib/python3/dist-packages/snapcraft/cmds.py", line 91, in snap
    meta.create(config.data, arches)
  File "/usr/lib/python3/dist-packages/snapcraft/meta.py", line 61, in create
    _write_package_yaml(meta_dir, config_data, arches)
  File "/usr/lib/python3/dist-packages/snapcraft/meta.py", line 72, in _write_package_yaml
    package_yaml = _compose_package_yaml(meta_dir, config_data, arches)
  File "/usr/lib/python3/dist-packages/snapcraft/meta.py", line 150, in _compose_package_yaml
    services = _wrap_services(services)
  File "/usr/lib/python3/dist-packages/snapcraft/meta.py", line 257, in _wrap_services
    startwrap = _wrap_exe(startparts[0])
  File "/usr/lib/python3/dist-packages/snapcraft/meta.py", line 228, in _wrap_exe
    common.run(['/bin/sh', tempf.name], cwd=snap_dir)
  File "/usr/lib/python3/dist-packages/snapcraft/common.py", line 50, in run
    subprocess.check_call(['/bin/sh', f.name] + cmd, **kwargs)
  File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/sh', '/tmp/tmp901gph_y', '/bin/sh', '/tmp/tmpygtkw4rc']' returned non-zero exit status 2

**Comment by howywang** [comment]
Another question, if i want to run some php or html files by your Apache service, where can I put the files?
Thank you.

**Comment by kyrofa** [comment]
Yeah that's [bug #1524374](https://bugs.launchpad.net/snapcraft/+bug/1524374). It's been fixed in Snapcraft 2, and the fix will be included in the new Snapcraft 1 release I'll crank out on Monday.

**Comment by kyrofa** [comment]
Regarding actually reusing this snap, I'm not sure I'd recommend it just yet. It's not the prettiest thing, and it wasn't written for reusability just yet (I'll be refactoring it into plugins as time goes on).

However, if you really feel like digging into it, you just need to create another `part` that uses the `copy` plugin, and place the HTML or PHP files into the `htdocs` directory.

**Comment by howywang** [comment]
Thank you for your guidance and support.
I will wait for Snapcraft 2.

**Comment by kyrofa** [comment]
Sounds good. Snapcraft 1.0.1 has been released with that bugfix, by the way.

**Comment by howywang** [comment]
Cool, I have updated to 1.0.1 just now.
But why can see the 2.0.1 at https://launchpad.net/snapcraft/+download ? Is it can be used?
Thanks
