### ISSUE TITLE
Failed doing pull for mdns-publisher

### ISSUE THREAD

**Issue by howywang** [kyrofa/owncloud-snap#9]
snapcraft version: 1.0.1
Ubuntu 15.04 -64bit

Failed doing pull for mdns-publisher: Command '['/bin/sh', '/tmp/tmp51ft919e', 'env', 'GOPATH=/home/u/Downloads/snap/owncloud-snap-master/parts/mdns-publisher/go', 'go', 'get', '-t', '-d', 'github.com/kyrofa/mdns-publisher']' returned non-zero exit status 1

**Comment by kyrofa** [comment]
Thanks for the report @howywang. Can you please publish more of the log? There's got to be more of an error than that, heh :smiley: .

**Comment by howywang** [comment]
Yes, which log do you want to get? ^^
